INSERT INTO products (name, price, color, cloth_type, length, size, material, description, image, status) VALUES
('Classic White T-Shirt', 499.00, 'White', 'Cotton', 'M', 'L', '100% Cotton', 'A staple for every wardrobe. This classic white t-shirt is made from premium cotton for all-day comfort.', 'demo_tshirt.png', 'active'),
('Blue Denim Jeans', 1299.00, 'Blue', 'Denim', 'Full', '32', 'Denim', 'Durable and stylish blue jeans. Perfect for casual wear with a comfortable fit.', 'demo_jeans.png', 'active'),
('Black Leather Jacket', 3499.00, 'Black', 'Leather', 'M', 'L', 'Genuine Leather', 'Upgrade your style with this sleek black leather jacket. Features zip pockets and a modern cut.', 'demo_jacket.png', 'active'),
('Floral Summer Dress', 899.00, 'Multicolor', 'Cotton Blend', 'Knee', 'M', 'Cotton', 'Light and breezy floral dress, perfect for hot summer days. Elegant and comfortable.', 'demo_dress.png', 'active'),
('Premium White Sneakers', 2499.00, 'White', 'Synthetic', 'N/A', '8', 'Leather', 'Stylish white sneakers for everyday wear.', 'sneakers.png', 'active'),
('Classic Grey Hoodie', 1499.00, 'Grey', 'Cotton', 'Full', 'M', 'Fleece', 'Warm and comfortable grey hoodie.', 'hoodie.png', 'active'),
('Classic Grey Hoodie', 1499.00, 'Grey', 'Cotton', 'Full', 'L', 'Fleece', 'Warm and comfortable grey hoodie in large size.', 'hoodie.png', 'active'),
('Elegant Wrist Watch', 5999.00, 'Silver', 'Metal', 'N/A', 'N/A', 'Stainless Steel', 'A luxury timepiece for special occasions.', 'watch.png', 'active'),
('Black Laptop Backpack', 1999.00, 'Black', 'Nylon', 'N/A', 'Standard', 'Water Resistant', 'Durable backpack with laptop compartment.', 'backpack.png', 'active'),
('Cool Aviator Sunglasses', 999.00, 'Gold', 'Metal', 'N/A', 'Standard', 'Glass', 'Classic aviator style sunglasses.', 'sunglasses.png', 'active'),
('Urban Streetwear Hoodie', 1699.00, 'Grey', 'Cotton', 'Full', 'XL', 'Cotton', 'Oversized aesthetic hoodie.', 'hoodie.png', 'active'),
('Sporty Running Shoes', 2299.00, 'White', 'Mesh', 'N/A', '9', 'Breathable Mesh', 'High performance running shoes.', 'sneakers.png', 'active'),
('Casual Daypack', 1299.00, 'Black', 'Canvas', 'N/A', 'Small', 'Canvas', 'Lightweight backpack for daily items.', 'backpack.png', 'active'),
('Gold Chronograph Watch', 7999.00, 'Gold', 'Metal', 'N/A', 'N/A', 'Gold Plated', 'Premium chronograph watch with gold finish.', 'watch.png', 'active'),
('Retro Polarized Shades', 1299.00, 'Black', 'Plastic', 'N/A', 'Standard', 'Polarized', 'Retro style sunglasses with UV protection.', 'sunglasses.png', 'active'),
('Cozy Fleece Pullover', 1399.00, 'Grey', 'Fleece', 'Full', 'S', 'Polyester', 'Soft fleece pullover for winter.', 'hoodie.png', 'active'),
('Canvas High Tops', 1899.00, 'White', 'Canvas', 'N/A', '10', 'Canvas', 'Classic high top sneakers.', 'sneakers.png', 'active'),
('Leather Strap Watch', 4599.00, 'Brown', 'Leather', 'N/A', 'N/A', 'Leather', 'Minimalist watch with genuine leather strap.', 'watch.png', 'active'),
('Tech Commuter Bag', 2999.00, 'Black', 'Polyester', 'N/A', 'Large', 'Waterproof', 'Tech-focused backpack with many compartments.', 'backpack.png', 'active'),
('Summer Wayfarers', 899.00, 'Tortoise', 'Acetate', 'N/A', 'Standard', 'Acetate', 'Stylish wayfarer sunglasses for summer.', 'sunglasses.png', 'active'),
('Heavyweight Cotton Hoodie', 1999.00, 'Grey', 'Cotton', 'Full', 'XXL', 'Heavy Cotton', 'Premium heavyweight hoodie.', 'hoodie.png', 'active'),
('Skate Boarding Shoes', 2199.00, 'White', 'Suede', 'N/A', '7', 'Suede', 'Durable shoes designed for skateboarding.', 'sneakers.png', 'active'),
('Travel Rucksack', 3499.00, 'Black', 'Nylon', 'N/A', 'XL', 'Ripstop', 'Large capacity rucksack for traveling.', 'backpack.png', 'active'),
('Smart Hybrid Watch', 9999.00, 'Black', 'Metal', 'N/A', 'N/A', 'Titanium', 'Hybrid smartwatch with fitness tracking.', 'watch.png', 'active');
